# This is a basic workflow to help you get started with Actions

name: wujian

# Controls when the workflow will run
on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 5 * * *'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

    # 配置安装 python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.2
          
        
      # 配置安装依赖包
      - name: Install requirements
        run: pip install -r requirements.txt
        
        
      # 配置安装依赖包
      - name: Install rsa
        run: pip install -r rsa.txt
        
      # 配置安装依赖包
      - name: Install smtplib
        run: pip install -r smtplib.txt
        
      # Runs a single command using the runners shell
      - name: working
        run: python SUSTYiBan.py ${{ secrets.CODE2 }} ${{ secrets. MOBILE}}  ${{ secrets. PSW}} ${{ secret.LOCATION}}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
